name: Integration tests

on:
  pull_request_review:
    types: [submitted, edited]
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'pre-commit-ci-update-config'
  workflow_dispatch:

jobs:
  integration_test:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'run-integration-tests') || github.event_name == 'workflow_dispatch' }}
    name: hs_${{ matrix.HYPERSPY_VERSION }}-rs_${{ matrix.ROSETTASCIIO_VERSION }}-ext_${{ matrix.EXTENSION_VERSION }}
    strategy:
      fail-fast: false
      matrix:
        EXTENSION_VERSION: ['release', 'dev']
        ROSETTASCIIO_VERSION: ['release', 'dev']
        HYPERSPY_VERSION: ['release', 'RnM', 'RnP']
    # Use the "reusable workflow" from the hyperspy organisation
    uses: hyperspy/.github/.github/workflows/integration_tests.yml@main
    with:
      # atomap depends on exspy
      EXTENSIONS: 'atomap hyperspy-gui-ipywidgets hyperspy-gui-traitsui'
      EXTENSION_VERSION: ${{ matrix.EXTENSION_VERSION }}
      HYPERSPY_VERSION: ${{ matrix.HYPERSPY_VERSION }}
      ROSETTASCIIO_VERSION: ${{ matrix.ROSETTASCIIO_VERSION }}
      PIP_EXTRAS: '[all,tests]'
      USE_CONDA: false
